#!/bin/bash
# Define some functions used by the network setup script.
#

# Usage: network_device_must_exist <PARAMETER NAME>
# Example:
#  > DEV_NAME=em1
#  > network_device_must_exist DEV_NAME
# where <PARAMETER NAME> is the name of a variable that contains the
# device name.
# Prints on stdout a message with <PARAMETER NAME> and it value.
# If the device does not exist 'exit' is called otherwise it returns.
network_device_must_exist() {
  if [ $# -ne 1 ] ; then 
    echo "!!!!! Missing argument to network-device_must_exist."
    exit 1;
  fi

  echo "# Checking that network ethernet NIC $1=${!1} exists."
  ethtool ${!1} > /dev/null >& /dev/null
  if [ "$?" != "0" ] ; then
    echo "!!!!!!  Ethernet device ${!1} does not exist."
    echo "Exiting"
    exit
  fi 
}


# Modify the a network device config to be for
# our external openstack network.
# Usage: setup_ext_device_networking <deviceName> <IPaddr> <netmask> [<gatewayIP>] 
# <deviceName> must be the name of a variable the holds a device name. It must
#     NOT be the device name itself.
setup_static_device_networking () {
  if [ "$#" != "4" ] && [ "$#" != "3" ] ; then
    echo "!!!! setup_ext_device_networking requires 3 or 4 arguments."
    exit 1
  fi

  # make sure the device exists.
  network_device_must_exist $1

  NET_DEVICE=${!1}  

  # Setup the cloud external network device.
  NET_CFG_FILE=/etc/sysconfig/network-scripts/ifcfg-${NET_DEVICE}
  echo "# Modifying '${NET_CFG_FILE}' configuration file."
  # Note: 'static' is deprecated so we use 'none'.
#  sed -i -e "/BOOTPROTO/s/=.*$/=\"none\"/"  $NET_CFG_FILE
  sed -i -e "/BOOTPROTO/s/=.*$/=\"static\"/"  $NET_CFG_FILE
  # Set IP Address
  grep -e "IPADDR[ ]*=" ${NET_CFG_FILE} > /dev/null
  if [ "$?" != "0" ] ; then
    # The IPADDR is not in the file yet so add it.
    sed -i "/BOOTPROTO/a\
IPADDR=$2" $NET_CFG_FILE
  else
    # It already had IPADDR specified so replace it.
    sed -i "/IPADDR[ ]*=/s/^.*$/IPADDR=$2/" $NET_CFG_FILE
  fi 
  # Set Netmask
  grep -e "NETMASK[ ]*=" $NET_CFG_FILE > /dev/null
  if [ "$?" != "0" ] ; then
    # The NETMASK is not in the file yet so add it after the IPADDR.
    sed -i -e "/IPADDR[ ]*=/a\
NETMASK=$3" $NET_CFG_FILE
  else
    # It already had NETMASK specified so replace it.
    sed -i "/NETMASK[ ]*=/s/^.*$/NETMASK=$3/" $NET_CFG_FILE
  fi 

  if [ $# -eq 4 ] ; then
    # Set GATEWAY
    grep -e "GATEWAY[ ]*=" $NET_CFG_FILE > /dev/null
    if [ "$?" != "0" ] ; then
      # The GATEWAY is not in the file yet so add it after the NETMASK.
      sed -i -e "/NETMASK[ ]*=/a\
GATEWAY=$4" $NET_CFG_FILE
    else
      # It already had GATEWAY specified so replace it.
      sed -i "/GATEWAY/s/^.*$/GATEWAY=$4/" $NET_CFG_FILE
    fi 
  else
    # There was not GATEWAY argument so dont do the keyway.
    grep -e "GATEWAY[ ]*=" $NET_CFG_FILE > /dev/null
    if [ "$?" != "0" ] ; then
      # The GATEWAY is not in the file yet so add it after the NETMASK.
      # But make it empty
      sed -i -e "/NETMASK[ ]*=/a\
#GATEWAY=" $NET_CFG_FILE
    else
      # It already had GATEWAY specified so replace it.
      sed -i "/GATEWAY/s/^.*$/#GATEWAY=/" $NET_CFG_FILE
    fi 
  fi

  # This is not our default route.
  sed -i -e "/^DEFROUTE/s/^/#/" $NET_CFG_FILE
  sed -i -e "/^IPV6_DEFROUTE/s/^/#/" /$NET_CFG_FILE
  sed -i -e "/^PEERDNS/s/^/#/" $NET_CFG_FILE
  sed -i -e "/^IPV6_PEERDNS/s/^/#/" $NET_CFG_FILE
  sed -i -e "/^PEERROUTES/s/^/#/" $NET_CFG_FILE
  sed -i -e "/^IPV6_PEERDNS/s/^/#/" $NET_CFG_FILE

  # Set the device name
  # Set Netmask
  grep 'DEVICE=' $NET_CFG_FILE > /dev/null
  if [ "$?" != "0" ] ; then
    # The DEVICE is not in the file yet so add it.
    sed -i "/NAME/a\
DEVICE=${NET_DEVICE}" $NET_CFG_FILE
  else
    # It already had DEVICE specified so replace it.
    sed -i "/DEVICE/s/=.*$/=${NET_DEVICE}/" $NET_CFG_FILE
  fi 

  # We want this device to start on boot.
  sed -i "/ONBOOT[ ]*=/s/^.*$/ONBOOT=yes/" $NET_CFG_FILE

  # We are not networkmanager controlled.
  grep -e '^NM_CONTROLLED=' $NET_CFG_FILE > /dev/null
  if [ $? -eq 0 ] ; then
    # It already had DEVICE specified so replace it.
    sed -i "/NM_CONTROLLED/s/=.*$/=no/" $NET_CFG_FILE
  fi 


}

# Setup the resolv.conf for the ext dns.
# Usage: setup_resolv <dnsIP> <searchDomain>
setup_resolv () {
  # We want to have our own name server added to the resolv.conf file.
  # See if it is already there.
  grep -e "$1" /etc/resolv.conf > /dev/null
  if [ "$?" != "0" ] ; then
    # The server address is not in the file yet so add it.
    sed -i -e "1i\
nameserver       $1" /etc/resolv.conf
  fi

  # We want to search our cloud domain. Add  to the resolv.conf file.
  # See if it is already there.
  grep -e "$2" /etc/resolv.conf > /dev/null
  if [ "$?" != "0" ] ; then
    # The search domain is not in the file yet so add it.
    sed -i "1a\
search      $2" /etc/resolv.conf
  fi

  # We want to search our cloud domain. Add  to the resolv.conf file.
  # See if it is already there.
  grep -e "^domain" /etc/resolv.conf > /dev/null
  if [ "$?" != "0" ] ; then
    sed -i "1 i\
domain      $2" /etc/resolv.conf
  else
    # The search domain is not in the file yet so add it.
    sed -i -e "/^domain/s/domain.*/domain      $2/" /etc/resolv.conf
  fi


}

# Get the IPv4 address if a network device.
# Usage: VALUE=$(get_device_ipaddr <deviceName>)
get_device_ipaddr () {

  if [ $# -ne 1 ] ; then 
    echo "!!!!! Need an <deviceName> argument to ${FUNCNAME[0]}."
    exit 1
  fi

  ip -f inet address show dev ${CLOUD_DATA_COMPUTE_DEVICE} | grep -e "inet" | sed -e "s/^.*inet //" -e "s/brd.*$//" -e "s/\/[0-9]*//"
}


# For neutron/openvswitch networking we want to move the static address of a physical
# device to a bridge.
# Usage: move_ip_from_phy_to_bridge <phyDeivceName> <promisc> <bridgeName>
# <phyDeviceName> - like 'em1'.
# <promisc>       - promiscuous mode 'yes' or 'no'.
# <bridgeName>    - name of the bridge device like 'br-ex'
move_ip_from_phy_to_bridge () {

  if [ $# -ne 3 ] ; then
    echo "Need 3 arguments to function ${FUNCNAME[0]}."
    exit 1
  fi

  # Config files for the network devices.
  IFCFG_DEVICE=/etc/sysconfig/network-scripts/ifcfg-$1
  IFCFG_BRIDGE=/etc/sysconfig/network-scripts/ifcfg-$3

  # Make sure we have not already done the work.
  if [ -f ${IFCFG_BRIDGE} ] ; then
    echo "# Bridge file '${IFCFG_BRIDGE}' already exists. Assuming that we don't have to modify it."
    return
  fi

  # Make sure that the physical device has a static address.
  grep -e "^IPADDR" ${IFCFG_DEVICE} > /dev/null
  if [ $? -ne 0 ] ; then
    echo "# The config file for device $1 has not been setup to be static."
    echo "!!!!! Unable to continue with bridge setup."
    exit 1
  fi

  touch ${IFCFG_BRIDGE}
  echo "DEVICE=${3}" >> ${IFCFG_BRIDGE}
  echo "TYPE=Bridge" >> ${IFCFG_BRIDGE}
  echo "ONBOOT=no" >> ${IFCFG_BRIDGE}
  echo "BOOTPROTO=none" >> ${IFCFG_BRIDGE}
  # get IPADDR, NETMASK and GATEWAY from the physical device config file.
  EXT_IPADDR=$(grep -e "IPADDR[ ]*=" ${IFCFG_DEVICE} | sed -e "s/^.*=[ ]*//")
  echo "IPADDR=${EXT_IPADDR}" >> ${IFCFG_BRIDGE}
  EXT_NETMASK=$(grep -e "NETMASK[ ]*=" ${IFCFG_DEVICE} | sed -e "s/^.*=[ ]*//")
  echo "NETMASK=${EXT_NETMASK}" >> ${IFCFG_BRIDGE}
  EXT_GATEWAY=$(grep -e "^[ ]*GATEWAY[ ]*=" ${IFCFG_DEVICE} | sed -e "s/^.*=[ ]*//" )
  if [ "${EXT_GATEWAY}" != "" ] ; then
    echo "GATEWAY=${EXT_GATEWAY}" >> ${IFCFG_BRIDGE}
  fi

  echo "# Modifying file '$1'."
  # comment out the static IP parameters
  sed -i -e "/^[ ]*IPADDR[ ]*=/s/^/#/" ${IFCFG_DEVICE}
  sed -i -e "/^[ ]*NETMASK[ ]*=/s/^/#/" ${IFCFG_DEVICE}
  sed -i -e "/^[ ]*GATEWAY[ ]*=/s/^/#/" ${IFCFG_DEVICE}
  sed -i -e "/^[ ]*BOOTPROTO[ ]*=/s/=.*/=none/" ${IFCFG_DEVICE}
  grep -e "PROMISC[ ]*=" ${IFCFG_DEVICE} > /dev/null
  if [ "$?" == "0" ] ; then
    # just change the value and uncomment.
    sed -i -e "/PROMISC/s/^.*\$/PROMISC=$2/" ${IFCFG_DEVICE}
  else
    # add the value
    sed -i -e "\$ a\
PROMISC=$2" ${IFCFG_DEVICE}
  fi

}

