#!/bin/bash
# Define some functions used to setup openstack on control, network
# and/or compute nodes.
#

# The UTIL_DIR parameter must contain the directory of the utility scripts.
if [ "${UTIL_DIR}" = "" ] ; then
  echo "!!!!!! Error: The envorinment variable UTIL_DIR must be defined before"
  echo " using the file 'openstack-fns".
  exit 1
fi

source_file ${UTIL_DIR}/network-fns

# install the latest rdo version. As of this writing the lastest
# was juno-1
install-rdo() {
  yum install -y https://rdo.fedorapeople.org/rdo-release.rpm
  
  yum install -y openstack-packstack

}

# We don't want the allinone network devices.
remove-rdo-allinone-network-devices() {
  neutron router-gateway-clear router1
  neutron subnet-delete public_subnet
  neutron net-delete public
  neutron router-interface-delete router1 private_subnet
  neutron subnet-delete private_subnet
  neutron net-delete private
  neutron router-delete router1
}

# RDO all in one does not completely setup the br-ex device. Lets do
# that.
# <phyDeviceName> - like 'em1'.
# <promisc>       - promiscuous mode 'yes' or 'no'.
# <bridgeName>    - name of the bridge device like 'br-ex'
fix-rdo-allinone-network-devices () {
  if [ $# -ne 3 ] ; then
    echo "Need 3 arguments to function ${FUNCNAME[0]}."
    exit 1
  fi
  move_ip_from_phy_to_bridge $1 $2 $3

  neutron router-create router1
  neutron net-create private
  neutron subnet-create --name private_subnet private 192.168.100.0/24 --allocation-pool start=192.168.100.224,end=192.168.100.254
  neutron router-interface-add router1 private_subnet

  neutron net-create public --router:external=True
  neutron subnet-create public ${CLOUD_EXT_COMPUTE_IPADDR_PREFIX}.0/24 --name public_subnet --enable_dhcp=False --allocation-pool start=${CLOUD_EXT_COMPUTE_IPADDR_PREFIX}.128,end=${CLOUD_EXT_COMPUTE_IPADDR_PREFIX}.159 --gateway=${CLOUD_EXT_ROUTER_IPADDR}
  neutron router-gateway-set router1 public
}
